### PR TITLE
revitalize

### PR DESCRIPTION
**Pull request by andrewazores**
use quarkus container-image build rather than s2i

replace run.sh with container-compose.yaml

~~The `JFRManager` piece isn't working when using `podman-compose up` yet. The containers are able to resolve each other by hostname and communicate over HTTP, but the JMX RMI lookup fails for some reason.~~

### CODE REVIEW

**Review by ebaron — COMMENTED** [review]
I'm having issues with this because I have both Podman and Docker installed on my system. The containers are built into the local Docker registry, but we want them to be in the Podman registry for use with `podman-compose`. I've been looking for a configuration property to build to the Podman registry, but no luck so far.

**Comment by andrewazores** [comment]
Ah. That sucks. I think I can fix that by replacing the `jib` build extension with the `docker` one, which allows for changing the name of the invoked executable - so I could set it to `podman` explicitly.

**Comment by ebaron** [comment]
> Ah. That sucks. I think I can fix that by replacing the `jib` build extension with the `docker` one, which allows for changing the name of the invoked executable - so I could set it to `podman` explicitly.

Sure, if it's not too much trouble. Otherwise I can uninstall Docker for now.

**Comment by andrewazores** [comment]
I left a comment on what seemed to be a relevant Quarkus issue for the Jib build plugin: https://github.com/quarkusio/quarkus/issues/16326#issuecomment-978025344

**Pull request merged**
